extern alias e6;
extern alias e24;
extern alias e31;
extern alias e3;
extern alias e25;
extern alias e2;
extern alias e23;
extern alias e29;

using n17 = e3::VL.Lib.Primitive.CacheRegion;
using n15 = _VL_Stride_Games_.Stride.Assets.Advanced;
using n3 = _VL_Stride_Games_.Stride.Utils;
using n7 = e31::VL.Stride;
using n10 = global::System.Collections.Generic;
using n8 = e2::VL.Lib.Basics.Resources;
using n13 = e6::Stride.Core;
using n16 = _CoreLibBasics_.Primitive.Advanced.Adaptive;
using n5 = e24::Stride.Engine;
using n12 = e25::Stride.Games;
using n1 = e2::VL.Core;
using n2 = global::System;
using n18 = e23::Stride.Core.Serialization.Contents;
using n4 = e2::VL.Core.CompilerServices;
using n20 = _VL_Stride_Games_.Stride;
using n19 = _VL_Stride_Runtime_TypeForwards_.Stride.API.Games.Utils.Advanced;
using n14 = e29::Stride.Rendering;
using n6 = global::System.Runtime.CompilerServices;
using n9 = _CoreLibBasics_.System.Resources.Advanced;
using n21 = _CoreLibBasics_.Primitive.Advanced;
using n11 = e31::VL.Stride.Engine;

namespace _VL_Stride_Games_.Stride.Utils
{
    [n1.ElementAttribute(TracingId = 21650U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "NFOYCtbjpVWPQqunXUGp2r", Name = "Game_NFOYCtbjpVWPQqunXUGp2r")]
    [n2.SerializableAttribute]
    public class Game_NFOYCtbjpVWPQqunXUGp2r : n1.VLObject, n2.IDisposable
    {
        [n4.CreateNewAttribute]
        public static n3.Game_NFOYCtbjpVWPQqunXUGp2r Create(n1.NodeContext Node_Context_In)
        {
            var instance = new Game_NFOYCtbjpVWPQqunXUGp2r(Node_Context_In, n1.VLObject.NewIdentity());
            return instance.__Create__(Node_Context_In);
        }

        [n4.CreateDefaultAttribute]
        public static n3.Game_NFOYCtbjpVWPQqunXUGp2r CreateDefault()
        {
            var instance = new Game_NFOYCtbjpVWPQqunXUGp2r(n1.NodeContext.Default, n1.VLObject.NewIdentity());
            return instance.__CreateDefault__();
        }

        public n3.Game_NFOYCtbjpVWPQqunXUGp2r Update(out n5.Game Output_Out)
        {
            var Output_1 = this.__p_Kew6AZghrTuNHBuSOPUGHa.GetResource(Resource_Out: out n5.Game Resource_0);
            Output_Out = Resource_0;
            n3.Game_NFOYCtbjpVWPQqunXUGp2r that_2 = this;
            if (this.__GetContext__().IsImmutable)
                that_2 = Output_1 != this.__p_Kew6AZghrTuNHBuSOPUGHa ? new Game_NFOYCtbjpVWPQqunXUGp2r(this)
                {__p_Kew6AZghrTuNHBuSOPUGHa = Output_1} : that_2;
            else
            {
                this.__p_Kew6AZghrTuNHBuSOPUGHa = Output_1;
            }

            return that_2;
        }

        public n3.Game_NFOYCtbjpVWPQqunXUGp2r __Create__(n1.NodeContext Node_Context_In)
        {
            n6.RuntimeHelpers.EnsureSufficientExecutionStack();
            var Result_0 = n7.Resources.GetGameProvider(nodeContext: Node_Context_In);
            n1.NodeContext Node_Context_1 = Node_Context_In.CreateSubContext("QuMTdtMDfhJOdxTx9ZFzce", "Kew6AZghrTuNHBuSOPUGHa", 21654U);
            var Output_2 = n9.Using_Process_MCPOIRh2AQkOT4VzsU5rcr<n8.IResourceProvider<n5.Game>, n5.Game>.Create(Node_Context: Node_Context_1);
            bool Update_3 = true;
            var Output_4 = Output_2;
            if (Update_3)
            {
                Output_4 = Output_2.Update(Input_In: Result_0);
            }

            n3.Game_NFOYCtbjpVWPQqunXUGp2r that_5 = this;
            this.__p_Kew6AZghrTuNHBuSOPUGHa = Output_4;
            return that_5;
        }

        public n3.Game_NFOYCtbjpVWPQqunXUGp2r __CreateDefault__()
        {
            n3.Game_NFOYCtbjpVWPQqunXUGp2r that_0 = this;
            this.__p_Kew6AZghrTuNHBuSOPUGHa = n9.Using_Process_MCPOIRh2AQkOT4VzsU5rcr<n8.IResourceProvider<n5.Game>, n5.Game>.CreateDefault();
            return that_0;
        }

        public void Dispose()
        {
            n1.CompilationHelper.SafeDispose(this.__p_Kew6AZghrTuNHBuSOPUGHa);
            return;
        }

        void n2.IDisposable.Dispose()
        {
            using var __current_services = __GetServiceRegistry__().MakeCurrentIfNone();
            Dispose();
        }

        [n1.ElementAttribute(TracingId = 21654U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "Kew6AZghrTuNHBuSOPUGHa", Name = "Using (Process)", IsManaged = true, IsAutoGenerated = true)]
        public n9.Using_Process_MCPOIRh2AQkOT4VzsU5rcr<n8.IResourceProvider<n5.Game>, n5.Game> __p_Kew6AZghrTuNHBuSOPUGHa;
        public Game_NFOYCtbjpVWPQqunXUGp2r(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
        {
        }

        internal Game_NFOYCtbjpVWPQqunXUGp2r(Game_NFOYCtbjpVWPQqunXUGp2r other): base(other)
        {
            this.__p_Kew6AZghrTuNHBuSOPUGHa = other.__p_Kew6AZghrTuNHBuSOPUGHa;
        }

        protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
        {
            return __WITH__(n1.CompilationHelper.GetValueOrExisting(values, "__p_Kew6AZghrTuNHBuSOPUGHa", in __p_Kew6AZghrTuNHBuSOPUGHa));
        }

        internal Game_NFOYCtbjpVWPQqunXUGp2r __WITH__(n9.Using_Process_MCPOIRh2AQkOT4VzsU5rcr<n8.IResourceProvider<n5.Game>, n5.Game> __p_Kew6AZghrTuNHBuSOPUGHa)
        {
            n3.Game_NFOYCtbjpVWPQqunXUGp2r that_0 = this;
            if (this.__GetContext__().IsImmutable)
                that_0 = __p_Kew6AZghrTuNHBuSOPUGHa != this.__p_Kew6AZghrTuNHBuSOPUGHa ? new Game_NFOYCtbjpVWPQqunXUGp2r(this)
                {__p_Kew6AZghrTuNHBuSOPUGHa = __p_Kew6AZghrTuNHBuSOPUGHa} : that_0;
            else
            {
                this.__p_Kew6AZghrTuNHBuSOPUGHa = __p_Kew6AZghrTuNHBuSOPUGHa;
            }

            return that_0;
        }
    }

    [n1.ElementAttribute(TracingId = 24576U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "OEQ5zbU2yU7NAEN04ZVLzQ", Name = "GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ")]
    [n2.SerializableAttribute]
    public class GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ : n1.VLObject, n2.IDisposable
    {
        [n4.CreateNewAttribute]
        public static n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ Create(n1.NodeContext Node_Context)
        {
            var instance = new GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ(Node_Context, n1.VLObject.NewIdentity());
            return instance.__Create__(Node_Context);
        }

        [n4.CreateDefaultAttribute]
        public static n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ CreateDefault()
        {
            var instance = new GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ(n1.NodeContext.Default, n1.VLObject.NewIdentity());
            return instance.__CreateDefault__();
        }

        public n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ GetScheduler(out n11.SchedulerSystem Output_Out)
        {
            n11.SchedulerSystem __auto_0 = this.Scheduler;
            Output_Out = __auto_0;
            return this;
        }

        public n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ Schedule(n12.GameSystemBase Game_System_In)
        {
            n11.SchedulerSystem __auto_0 = this.Scheduler;
            __auto_0.Schedule(gameSystem: Game_System_In);
            return this;
        }

        public n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ __Create__(n1.NodeContext Node_Context)
        {
            n6.RuntimeHelpers.EnsureSufficientExecutionStack();
            n1.NodeContext Node_Context_0 = Node_Context.CreateSubContext("QuMTdtMDfhJOdxTx9ZFzce", "K5kA9C0IoTJMIkr0wAybYb", 24579U);
            var Output_1 = n3.Game_NFOYCtbjpVWPQqunXUGp2r.Create(Node_Context_In: Node_Context_0);
            var State_Output_3 = Output_1.Update(Output_Out: out n5.Game Output_2);
            n12.IGame Input_4 = (n12.IGame)Output_2;
            var Services_5 = Input_4.Services;
            n13.IServiceRegistry Input_6 = (n13.IServiceRegistry)Services_5;
            var Result_7 = ((n13.IServiceRegistry)Input_6).GetService<n11.SchedulerSystem>();
            n11.SchedulerSystem __auto_8 = Result_7;
            n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ that_9 = this;
            this.Scheduler = Result_7;
            this.__p_K5kA9C0IoTJMIkr0wAybYb = State_Output_3;
            return that_9;
        }

        public n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ __CreateDefault__()
        {
            n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ that_0 = this;
            this.Scheduler = default(n11.SchedulerSystem);
            this.__p_K5kA9C0IoTJMIkr0wAybYb = n3.Game_NFOYCtbjpVWPQqunXUGp2r.CreateDefault();
            return that_0;
        }

        public void Dispose()
        {
            n1.CompilationHelper.SafeDispose(this.__p_K5kA9C0IoTJMIkr0wAybYb);
            return;
        }

        void n2.IDisposable.Dispose()
        {
            using var __current_services = __GetServiceRegistry__().MakeCurrentIfNone();
            Dispose();
        }

        [n1.ElementAttribute(TracingId = 24586U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "BUrhv7bjouPOrq61VCvrYB", Name = "Scheduler")]
        public n11.SchedulerSystem Scheduler;
        [n1.ElementAttribute(TracingId = 24579U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "K5kA9C0IoTJMIkr0wAybYb", Name = "Game", IsManaged = true, IsAutoGenerated = true)]
        public n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_K5kA9C0IoTJMIkr0wAybYb;
        public GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
        {
        }

        internal GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ(GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ other): base(other)
        {
            this.Scheduler = other.Scheduler;
            this.__p_K5kA9C0IoTJMIkr0wAybYb = other.__p_K5kA9C0IoTJMIkr0wAybYb;
        }

        protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
        {
            return __WITH__(n1.CompilationHelper.GetValueOrExisting(values, "Scheduler", in Scheduler), n1.CompilationHelper.GetValueOrExisting(values, "__p_K5kA9C0IoTJMIkr0wAybYb", in __p_K5kA9C0IoTJMIkr0wAybYb));
        }

        internal GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ __WITH__(n11.SchedulerSystem Scheduler, n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_K5kA9C0IoTJMIkr0wAybYb)
        {
            n3.GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ that_0 = this;
            if (this.__GetContext__().IsImmutable)
                that_0 = Scheduler != this.Scheduler || __p_K5kA9C0IoTJMIkr0wAybYb != this.__p_K5kA9C0IoTJMIkr0wAybYb ? new GameSystemScheduler_OEQ5zbU2yU7NAEN04ZVLzQ(this)
                {Scheduler = Scheduler, __p_K5kA9C0IoTJMIkr0wAybYb = __p_K5kA9C0IoTJMIkr0wAybYb} : that_0;
            else
            {
                this.Scheduler = Scheduler;
                this.__p_K5kA9C0IoTJMIkr0wAybYb = __p_K5kA9C0IoTJMIkr0wAybYb;
            }

            return that_0;
        }
    }

    [n1.ElementAttribute(TracingId = 24635U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "A5jsSvRdG3aQXzlHCbUc8D", Name = "RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D")]
    [n2.SerializableAttribute]
    public class RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D : n1.VLObject, n2.IDisposable
    {
        [n4.CreateNewAttribute]
        public static n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D Create(n1.NodeContext Node_Context)
        {
            var instance = new RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D(Node_Context, n1.VLObject.NewIdentity());
            return instance.__Create__(Node_Context);
        }

        [n4.CreateDefaultAttribute]
        public static n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D CreateDefault()
        {
            var instance = new RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D(n1.NodeContext.Default, n1.VLObject.NewIdentity());
            return instance.__CreateDefault__();
        }

        public n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D GetScheduler(out n11.SchedulerSystem Output_Out)
        {
            n11.SchedulerSystem __auto_0 = this.Scheduler;
            Output_Out = __auto_0;
            return this;
        }

        public n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D Schedule(n14.IGraphicsRendererBase Renderer_In)
        {
            n11.SchedulerSystem __auto_0 = this.Scheduler;
            __auto_0.Schedule(renderer: Renderer_In);
            return this;
        }

        public n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D __Create__(n1.NodeContext Node_Context)
        {
            n6.RuntimeHelpers.EnsureSufficientExecutionStack();
            n1.NodeContext Node_Context_0 = Node_Context.CreateSubContext("QuMTdtMDfhJOdxTx9ZFzce", "HlqP7SeZm0GPiBhfMyrdtk", 24639U);
            var Output_1 = n3.Game_NFOYCtbjpVWPQqunXUGp2r.Create(Node_Context_In: Node_Context_0);
            var State_Output_3 = Output_1.Update(Output_Out: out n5.Game Output_2);
            n12.IGame Input_4 = (n12.IGame)Output_2;
            var Services_5 = Input_4.Services;
            n13.IServiceRegistry Input_6 = (n13.IServiceRegistry)Services_5;
            var Result_7 = ((n13.IServiceRegistry)Input_6).GetService<n11.SchedulerSystem>();
            n11.SchedulerSystem __auto_8 = Result_7;
            n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D that_9 = this;
            this.Scheduler = Result_7;
            this.__p_HlqP7SeZm0GPiBhfMyrdtk = State_Output_3;
            return that_9;
        }

        public n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D __CreateDefault__()
        {
            n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D that_0 = this;
            this.Scheduler = default(n11.SchedulerSystem);
            this.__p_HlqP7SeZm0GPiBhfMyrdtk = n3.Game_NFOYCtbjpVWPQqunXUGp2r.CreateDefault();
            return that_0;
        }

        public void Dispose()
        {
            n1.CompilationHelper.SafeDispose(this.__p_HlqP7SeZm0GPiBhfMyrdtk);
            return;
        }

        void n2.IDisposable.Dispose()
        {
            using var __current_services = __GetServiceRegistry__().MakeCurrentIfNone();
            Dispose();
        }

        [n1.ElementAttribute(TracingId = 24652U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "TEbq17BDKunL7Bafj0cmnz", Name = "Scheduler")]
        public n11.SchedulerSystem Scheduler;
        [n1.ElementAttribute(TracingId = 24639U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "HlqP7SeZm0GPiBhfMyrdtk", Name = "Game", IsManaged = true, IsAutoGenerated = true)]
        public n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_HlqP7SeZm0GPiBhfMyrdtk;
        public RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
        {
        }

        internal RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D(RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D other): base(other)
        {
            this.Scheduler = other.Scheduler;
            this.__p_HlqP7SeZm0GPiBhfMyrdtk = other.__p_HlqP7SeZm0GPiBhfMyrdtk;
        }

        protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
        {
            return __WITH__(n1.CompilationHelper.GetValueOrExisting(values, "Scheduler", in Scheduler), n1.CompilationHelper.GetValueOrExisting(values, "__p_HlqP7SeZm0GPiBhfMyrdtk", in __p_HlqP7SeZm0GPiBhfMyrdtk));
        }

        internal RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D __WITH__(n11.SchedulerSystem Scheduler, n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_HlqP7SeZm0GPiBhfMyrdtk)
        {
            n3.RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D that_0 = this;
            if (this.__GetContext__().IsImmutable)
                that_0 = Scheduler != this.Scheduler || __p_HlqP7SeZm0GPiBhfMyrdtk != this.__p_HlqP7SeZm0GPiBhfMyrdtk ? new RendererScheduler_A5jsSvRdG3aQXzlHCbUc8D(this)
                {Scheduler = Scheduler, __p_HlqP7SeZm0GPiBhfMyrdtk = __p_HlqP7SeZm0GPiBhfMyrdtk} : that_0;
            else
            {
                this.Scheduler = Scheduler;
                this.__p_HlqP7SeZm0GPiBhfMyrdtk = __p_HlqP7SeZm0GPiBhfMyrdtk;
            }

            return that_0;
        }
    }
}

namespace _VL_Stride_Games_.Stride.Assets.Advanced
{
    [n1.ElementAttribute(TracingId = 24707U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "EjW2888H8y2L6BeMp02X17", Name = "GameAsset_EjW2888H8y2L6BeMp02X17")]
    [n2.SerializableAttribute]
    public class GameAsset_EjW2888H8y2L6BeMp02X17<T> : n1.VLObject, n2.IDisposable where T : class
    {
        [n4.CreateNewAttribute]
        public static n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> Create<AdM>(n1.NodeContext Node_Context)
            where AdM : struct, n16.IAdaptiveCreateDefault<T>
        {
            var instance = new GameAsset_EjW2888H8y2L6BeMp02X17<T>(Node_Context, n1.VLObject.NewIdentity());
            return instance.__Create__<AdM>(Node_Context);
        }

        [n4.CreateDefaultAttribute]
        public static n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> CreateDefault<AdM>()
            where AdM : struct, n16.IAdaptiveCreateDefault<T>
        {
            var instance = new GameAsset_EjW2888H8y2L6BeMp02X17<T>(n1.NodeContext.Default, n1.VLObject.NewIdentity());
            return instance.__CreateDefault__<AdM>();
        }

        public n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> Update<AdM>(string Url_In, bool Reload_In, out T Output_Out)
            where AdM : struct, n16.IAdaptiveCreateDefault<T>
        {
            var w_0 = default(AdM);
            bool Dispose_Cached_Outputs_1 = false;
            var manager_2 = this.__cache_NyqaqQzdyf4N32VMoe4eyY;
            if (manager_2 is null)
            {
                w_0.CreateDefault(out T __out_0);
                manager_2 = new n17.Manager<n2.ValueTuple<string>, n2.ValueTuple<T>>(n2.ValueTuple.Create(__out_0));
            }

            var inputs_3 = n2.ValueTuple.Create(Url_In);
            var outputs_4 = manager_2.Outputs;
            var Has_Changed_5 = Reload_In || manager_2.InputsChanged(inputs_3);
            if (Has_Changed_5)
            {
                if (Dispose_Cached_Outputs_1)
                    manager_2.DisposeOutputs();
                var state_6 = n1.CompilationHelper.Restore<__FjtDxE6cZ9dO1OEAJuVTMu>(manager_2.State, __GetContext__());
                if (state_6 == null)
                {
                    state_6 = new __FjtDxE6cZ9dO1OEAJuVTMu(__GetContext__(), n1.VLObject.NewIdentity());
                    n1.NodeContext Node_Context_7 = __GetContext__().CreateSubContext("QuMTdtMDfhJOdxTx9ZFzce", "Qyxbsu6Wj6GMP8ORdQ0ojZ", 24729U);
                    var Output_8 = n3.Game_NFOYCtbjpVWPQqunXUGp2r.Create(Node_Context_In: Node_Context_7);
                    state_6.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = Output_8;
                }

                var State_Output_10 = state_6.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ.Update(Output_Out: out n5.Game Output_9);
                n18.ContentManager Content_Manager_11 = default(n18.ContentManager);
                n19._Operations_.LoadAsset<n5.Game, T>(Game_In: Output_9, Content_Manager_In: Content_Manager_11, Path_In: Url_In, Result_Out: out T Result_12);
                if (state_6.__GetContext__().IsImmutable)
                    state_6 = State_Output_10 != state_6.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ ? new __FjtDxE6cZ9dO1OEAJuVTMu(state_6)
                    {__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = State_Output_10} : state_6;
                else
                {
                    state_6.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = State_Output_10;
                }

                outputs_4 = n2.ValueTuple.Create(Result_12);
                manager_2 = manager_2.Update(inputs_3, __GetContext__().IsImmutable, Dispose_Cached_Outputs_1, state_6, outputs_4);
            }
            else
            {
                manager_2.Update(inputs_3, __GetContext__().IsImmutable, Dispose_Cached_Outputs_1);
            }

            var __auto_13 = outputs_4.Item1;
            Output_Out = __auto_13;
            n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> that_14 = this;
            if (this.__GetContext__().IsImmutable)
                that_14 = manager_2 != this.__cache_NyqaqQzdyf4N32VMoe4eyY ? new GameAsset_EjW2888H8y2L6BeMp02X17<T>(this)
                {__cache_NyqaqQzdyf4N32VMoe4eyY = manager_2} : that_14;
            else
            {
                this.__cache_NyqaqQzdyf4N32VMoe4eyY = manager_2;
            }

            return that_14;
        }

        public n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> __Create__<AdM>(n1.NodeContext Node_Context)
            where AdM : struct, n16.IAdaptiveCreateDefault<T>
        {
            n6.RuntimeHelpers.EnsureSufficientExecutionStack();
            var w_0 = default(AdM);
            n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> that_1 = this;
            this.__cache_NyqaqQzdyf4N32VMoe4eyY = null;
            return that_1;
        }

        public n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> __CreateDefault__<AdM>()
            where AdM : struct, n16.IAdaptiveCreateDefault<T>
        {
            var w_0 = default(AdM);
            n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> that_1 = this;
            this.__cache_NyqaqQzdyf4N32VMoe4eyY = null;
            return that_1;
        }

        public void Dispose()
        {
            n1.CompilationHelper.SafeDispose(this.__cache_NyqaqQzdyf4N32VMoe4eyY);
            return;
        }

        void n2.IDisposable.Dispose()
        {
            using var __current_services = __GetServiceRegistry__().MakeCurrentIfNone();
            Dispose();
        }

        [n1.ElementAttribute(TracingId = 24712U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "NyqaqQzdyf4N32VMoe4eyY", Name = "Cache", IsManaged = true, IsAutoGenerated = true)]
        public n17.Manager<n2.ValueTuple<string>, n2.ValueTuple<T>> __cache_NyqaqQzdyf4N32VMoe4eyY = null;
        public GameAsset_EjW2888H8y2L6BeMp02X17(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
        {
        }

        internal GameAsset_EjW2888H8y2L6BeMp02X17(GameAsset_EjW2888H8y2L6BeMp02X17<T> other): base(other)
        {
            this.__cache_NyqaqQzdyf4N32VMoe4eyY = other.__cache_NyqaqQzdyf4N32VMoe4eyY;
        }

        protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
        {
            return __WITH__(n1.CompilationHelper.GetValueOrExisting(values, "__cache_NyqaqQzdyf4N32VMoe4eyY", in __cache_NyqaqQzdyf4N32VMoe4eyY));
        }

        internal GameAsset_EjW2888H8y2L6BeMp02X17<T> __WITH__(n17.Manager<n2.ValueTuple<string>, n2.ValueTuple<T>> __cache_NyqaqQzdyf4N32VMoe4eyY)
        {
            n15.GameAsset_EjW2888H8y2L6BeMp02X17<T> that_0 = this;
            if (this.__GetContext__().IsImmutable)
                that_0 = __cache_NyqaqQzdyf4N32VMoe4eyY != this.__cache_NyqaqQzdyf4N32VMoe4eyY ? new GameAsset_EjW2888H8y2L6BeMp02X17<T>(this)
                {__cache_NyqaqQzdyf4N32VMoe4eyY = __cache_NyqaqQzdyf4N32VMoe4eyY} : that_0;
            else
            {
                this.__cache_NyqaqQzdyf4N32VMoe4eyY = __cache_NyqaqQzdyf4N32VMoe4eyY;
            }

            return that_0;
        }

        [n1.ElementAttribute(DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "FjtDxE6cZ9dO1OEAJuVTMu", Name = "__FjtDxE6cZ9dO1OEAJuVTMu")]
        [n2.SerializableAttribute]
        public class __FjtDxE6cZ9dO1OEAJuVTMu : n1.VLObject, n2.IDisposable
        {
            public void Dispose()
            {
                n1.CompilationHelper.SafeDispose(this.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ);
                return;
            }

            [n1.ElementAttribute(TracingId = 24729U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "Qyxbsu6Wj6GMP8ORdQ0ojZ", Name = "Game", IsManaged = true, IsAutoGenerated = true)]
            public n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_Qyxbsu6Wj6GMP8ORdQ0ojZ;
            public __FjtDxE6cZ9dO1OEAJuVTMu(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
            {
            }

            internal __FjtDxE6cZ9dO1OEAJuVTMu(__FjtDxE6cZ9dO1OEAJuVTMu other): base(other)
            {
                this.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = other.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ;
            }

            protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
            {
                return __WITH__(n1.CompilationHelper.GetValueOrExisting(values, "__p_Qyxbsu6Wj6GMP8ORdQ0ojZ", in __p_Qyxbsu6Wj6GMP8ORdQ0ojZ));
            }

            internal __FjtDxE6cZ9dO1OEAJuVTMu __WITH__(n3.Game_NFOYCtbjpVWPQqunXUGp2r __p_Qyxbsu6Wj6GMP8ORdQ0ojZ)
            {
                __FjtDxE6cZ9dO1OEAJuVTMu that_0 = this;
                if (this.__GetContext__().IsImmutable)
                    that_0 = __p_Qyxbsu6Wj6GMP8ORdQ0ojZ != this.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ ? new __FjtDxE6cZ9dO1OEAJuVTMu(this)
                    {__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = __p_Qyxbsu6Wj6GMP8ORdQ0ojZ} : that_0;
                else
                {
                    this.__p_Qyxbsu6Wj6GMP8ORdQ0ojZ = __p_Qyxbsu6Wj6GMP8ORdQ0ojZ;
                }

                return that_0;
            }
        }
    }
}

namespace _VL_Stride_Games_.Stride
{
    [n1.ElementAttribute(TracingId = 24797U, DocumentId = "QuMTdtMDfhJOdxTx9ZFzce", PersistentId = "OfoGgjpFBuQOO6WH36N2O3", Name = "VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3")]
    [n2.SerializableAttribute]
    public class VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 : n1.VLObject, n2.IDisposable
    {
        [n4.CreateNewAttribute]
        public static n20.VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 Create(n1.NodeContext Node_Context)
        {
            var instance = new VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3(Node_Context, n1.VLObject.NewIdentity());
            return instance.__Create__(Node_Context);
        }

        [n4.CreateDefaultAttribute]
        public static n20.VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 CreateDefault()
        {
            var instance = new VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3(n1.NodeContext.Default, n1.VLObject.NewIdentity());
            return instance.__CreateDefault__();
        }

        public n20.VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 Update()
        {
            return this;
        }

        public n20.VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 __Create__(n1.NodeContext Node_Context)
        {
            n6.RuntimeHelpers.EnsureSufficientExecutionStack();
            return this;
        }

        public n20.VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 __CreateDefault__()
        {
            return this;
        }

        public void Dispose()
        {
            return;
        }

        void n2.IDisposable.Dispose()
        {
            using var __current_services = __GetServiceRegistry__().MakeCurrentIfNone();
            Dispose();
        }

        public VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3(n1.NodeContext __context__, uint __identity__): base(__context__, __identity__)
        {
        }

        internal VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3(VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 other): base(other)
        {
        }

        protected override n1.IVLObject __With__(n10.IReadOnlyDictionary<string, n2.Object> values)
        {
            return __WITH__();
        }

        internal VL_Stride_GamesApplication_OfoGgjpFBuQOO6WH36N2O3 __WITH__()
        {
            return this;
        }
    }
}

namespace _VL_Stride_Games_
{
    public struct __AdaptiveImplementations__QuMTdtMDfhJOdxTx9ZFzce : n16.IAdaptiveCreateDefault<n5.Game>
    {
        public void CreateDefault(out n5.Game Output_Out)
        {
            n21._Operations_.CreateDefault_Generic<n5.Game>(Output_Out: out n5.Game Output_0);
            Output_Out = Output_0;
            return;
        }
    }
}